version: "3.8"

services:
  software-library:
    image: edcv593/software-library:latest
    container_name: software-library
    restart: unless-stopped
    ports:
      - "8899:8899"
    volumes:
      # 软件文件目录：程序需要写入 uploads，因此不要使用 :ro
      - /tmp/zfsv3/nvme17/13040705017/data/共享数据:/data
      # 程序配置、用户、扫描结果持久化
      - /tmp/zfsv3/nvme17/13040705017/data/software-library:/app/data
    environment:
      - LIB_ROOT_DIR=/data
      - LIB_PORT=8899
      - LIB_DATA_DIR=/app/data
      - LIB_WATCH_INTERVAL=3600
