// Local preview-admin required. Synthetic tasks and mocked actions; no downloads.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.QUEUE_TEST_URL || 'http://127.0.0.1:8932');await p.locator('#loginUser').fill('preview-admin');await p.locator('#loginPass').fill('PreviewOnly-2026');await p.locator('.modal').getByRole('button',{name:'登录',exact:true}).click();await p.getByText('登录成功',{exact:true}).waitFor();
await p.evaluate(()=>{pollQueue=async()=>drawQueue();queueTasks=Array.from({length:35},(_,i)=>({id:String(i),filename:'setup'+i+'.exe',software:'tool',status:i<5?'downloading':i<20?'failed':i<30?'completed':'cancelled',bytes:10,total:100,attempts:1,error:i>=5&&i<20?'HTTP 403':''}));currentView='queue';render();});
assert.equal(await p.locator('.queue-task').count(),12);assert.match(await p.locator('.queue-task').first().innerText(),/下载中/);await p.getByRole('button',{name:'失败 15',exact:true}).click();assert.equal(await p.locator('.queue-task').count(),12);await p.getByLabel('下载任务分页').getByRole('button',{name:'下一页',exact:true}).click();assert.equal(await p.locator('.queue-task').count(),3);
await p.getByLabel('搜索下载任务',{exact:true}).fill('setup1 403');assert.equal(await p.locator('.queue-task').count(),10);await p.evaluate(()=>drawQueue());assert.equal(await p.getByLabel('搜索下载任务',{exact:true}).inputValue(),'setup1 403');assert.equal(await p.getByLabel('搜索下载任务',{exact:true}).evaluate(e=>document.activeElement===e),true);
await p.evaluate(()=>{window.calls=[];transferApi=async(url,data)=>{calls.push(data);await new Promise(r=>setTimeout(r,250));return true;};});const retry=p.locator('.queue-task').first().getByRole('button',{name:'重试',exact:true});await retry.click();assert.equal(await retry.isDisabled(),true);await p.waitForFunction(()=>queueActionsPending.size===0);assert.equal(await p.evaluate(()=>calls.length),1);
await p.getByLabel('搜索下载任务',{exact:true}).fill('<img src=x>');assert.equal(await p.locator('.queue-task').count(),0);await p.getByRole('button',{name:'重置任务筛选',exact:true}).click();assert.equal(await p.locator('.queue-task').count(),12);await p.getByRole('button',{name:'已完成 10',exact:true}).click();assert.equal(await p.locator('.queue-task').count(),10);assert.equal(await p.getByRole('button',{name:'重试',exact:true}).count(),0);
await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS status counts, active ordering, pagination, multi-term error search, refresh input focus, duplicate action protection, empty/reset, completed actions and mobile layout');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
