// Local preview-admin test account required. Uses synthetic data; no version mutations.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.VERSION_TEST_URL || 'http://127.0.0.1:8931');await p.locator('#loginUser').fill('preview-admin');await p.locator('#loginPass').fill('PreviewOnly-2026');await p.locator('.modal').getByRole('button',{name:'登录',exact:true}).click();await p.getByText('登录成功',{exact:true}).waitFor();
await p.evaluate(()=>{ALL_DATA=[{name:'tool',displayName:'工具',categoryId:'',versions:Array.from({length:30},(_,i)=>({path:'v'+i+'.exe',filename:'v'+i+'.exe',version:String(i),arch:i%2?'arm64':'x64',channel:i<6?'archive':'stable',reviewState:i>=6&&i<11?'pending':i>=11&&i<14?'rejected':'approved',date:'2026-09-01',size:100,sizeText:'100 B'}))}];goVersion('tool');});
assert.equal(await p.locator('.version-managed').count(),12);await p.getByRole('button',{name:'全选本页版本',exact:true}).click();assert.equal(await p.evaluate(()=>versionSelection.size),12);await p.getByLabel('版本列表分页').getByRole('button',{name:'下一页',exact:true}).click();assert.match(await p.locator('#container').innerText(),/12 项不在当前页/);
await p.getByLabel('版本发布状态',{exact:true}).selectOption('pending');assert.equal(await p.locator('.version-managed').count(),5);await p.getByLabel('版本发布状态',{exact:true}).selectOption('published');assert.match(await p.locator('.browse-summary').innerText(),/共 16 个匹配版本/);await p.getByLabel('显示历史版本',{exact:true}).check();assert.match(await p.locator('.browse-summary').innerText(),/共 22 个匹配版本/);
await p.getByRole('button',{name:'重置版本筛选',exact:true}).click();await p.getByLabel('筛选版本',{exact:true}).fill('v2 x64');assert.equal(await p.locator('.version-managed').count(),5);await p.evaluate(()=>render());assert.equal(await p.getByLabel('筛选版本',{exact:true}).inputValue(),'v2 x64');
const first=p.locator('.version-managed').first();assert.equal(await first.getByRole('button',{name:'编辑版本',exact:true}).isVisible(),false);await first.locator('summary').filter({hasText:'更多操作'}).click();await first.getByRole('button',{name:'编辑版本',exact:true}).click();await p.getByRole('button',{name:'取消',exact:true}).click();
await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await p.evaluate(()=>{SESSION=null;render();});assert.equal(await p.getByLabel('版本发布状态',{exact:true}).count(),0);assert.match(await p.locator('.browse-summary').innerText(),/共 16 个匹配版本/);assert.equal(await p.getByRole('button',{name:'批准发布',exact:true}).count(),0);assert.deepEqual(errors,[]);console.log('PASS version pagination, page-only selection, hidden selection counts, review/history filters, multi-term search, retained state, collapsed tools, mobile layout and reader visibility');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
