// Local preview-admin test account required. Synthetic data; movement is mocked.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.MANAGER_TEST_URL || 'http://127.0.0.1:8930');await p.locator('#loginUser').fill('preview-admin');await p.locator('#loginPass').fill('PreviewOnly-2026');await p.locator('.modal').getByRole('button',{name:'登录',exact:true}).click();await p.waitForFunction(()=>SESSION?.role==='admin');await p.getByText('登录成功',{exact:true}).waitFor();
await p.evaluate(()=>{CATEGORIES=[{id:'a',name:'工具',parentId:''},{id:'b',name:'子分类',parentId:'a'}];ALL_DATA=Array.from({length:45},(_,i)=>({name:'tool-'+i,displayName:'工具 '+i,categoryId:i===44?'':i%2?'a':'b',versions:[{path:'file'+i,filename:'test'+i+'.exe',version:'1.2',arch:'x64'}]}));openAdminSection('software');});
assert.equal(await p.locator('.catalog-software-row').count(),20);
await p.getByRole('button',{name:'全选当前页',exact:true}).click();await p.locator('.catalog-manager').getByRole('button',{name:'下一页',exact:true}).click();assert.match(await p.getByLabel('批量操作',{exact:true}).innerText(),/20 项不在当前页/);
await p.getByRole('button',{name:'只看已选',exact:true}).click();assert.equal(await p.locator('.catalog-software-row').count(),20);await p.getByRole('checkbox',{name:'选择 工具 0',exact:true}).click();assert.equal(await p.locator('.catalog-software-row').count(),19);
await p.getByLabel('批量移动目标分类',{exact:true}).selectOption('b');await p.getByRole('button',{name:'移动所选',exact:true}).click();assert.equal(await p.locator('.move-review li').count(),19);await p.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await p.evaluate(()=>selectedSoftware.size),19);
await p.evaluate(()=>{window.savedMove=null;saveCatalog=async data=>{window.savedMove=data;closeModal();return true;};});await p.getByRole('button',{name:'移动所选',exact:true}).click();await p.getByRole('button',{name:'确认移动',exact:true}).click();assert.deepEqual(await p.evaluate(()=>({count:window.savedMove.names.length,target:window.savedMove.categoryId,selected:selectedSoftware.size})),{count:19,target:'b',selected:0});
await p.getByLabel('筛选软件分类',{exact:true}).selectOption('');assert.equal(await p.locator('.catalog-software-row').count(),1);await p.getByLabel('筛选软件分类',{exact:true}).selectOption('a');assert.match(await p.locator('.catalog-manager').innerText(),/共 44 项/);
await p.getByRole('button',{name:'重置筛选',exact:true}).click();await p.getByLabel('管理软件搜索',{exact:true}).fill('test3 x64');assert.equal(await p.locator('.catalog-software-row').count(),11);await p.evaluate(()=>render());assert.equal(await p.getByLabel('管理软件搜索',{exact:true}).inputValue(),'test3 x64');assert.equal(await p.locator('.catalog-software-row').count(),11);
await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS category descendants/uncategorized, cross-page selection, selected-only deselect, move review cancel/confirm, multi-term search, retained filters and mobile layout');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
