// Local preview-admin required. Synthetic users; account changes are mocked.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACCOUNT_TEST_URL || 'http://127.0.0.1:8934');await p.locator('#loginUser').fill('preview-admin');await p.locator('#loginPass').fill('PreviewOnly-2026');await p.locator('.modal').getByRole('button',{name:'登录',exact:true}).click();await p.getByText('登录成功',{exact:true}).waitFor();
await p.evaluate(()=>{window.testUsers=Array.from({length:45},(_,i)=>({username:i===0?'preview-admin':'user'+i,role:i===0?'admin':'user',email:i===4?'':'person'+i+'@example.com',emailVerified:i!==4,signupPending:i===1,disabled:i===1||i===2,canDownload:i!==3}));const original=api;api=async(url,opt)=>{if(url==='/api/users')return {success:true,users:JSON.parse(JSON.stringify(testUsers))};if(url.startsWith('/api/users/')&&opt?.method==='PUT'){const u=testUsers.find(u=>u.username===decodeURIComponent(url.split('/').at(-1)));Object.assign(u,opt.body);if(opt.body.disabled===false)u.signupPending=false;return {success:true};}return original(url,opt);};openAdminSection('accounts');});
await p.getByLabel('账号状态筛选',{exact:true}).waitFor();assert.equal(await p.locator('#userList .user-row').count(),20);assert.match(await p.locator('#userList .user-row').first().innerText(),/待审批/);await p.getByLabel('用户列表分页').getByRole('button',{name:'下一页',exact:true}).click();assert.match(await p.locator('#userList .browse-summary').innerText(),/21–40/);
await p.getByLabel('账号状态筛选',{exact:true}).selectOption('pending');assert.equal(await p.locator('#userList .user-row').count(),1);await p.getByRole('button',{name:'批准注册',exact:true}).click();await p.waitForFunction(()=>!testUsers[1].signupPending);await p.getByLabel('账号状态筛选',{exact:true}).waitFor();assert.equal(await p.getByLabel('账号状态筛选',{exact:true}).inputValue(),'pending');assert.equal(await p.locator('#userList .user-row').count(),0);
await p.getByLabel('账号状态筛选',{exact:true}).selectOption('disabled');assert.equal(await p.locator('#userList .user-row').count(),1);await p.getByLabel('账号状态筛选',{exact:true}).selectOption('paused');assert.match(await p.locator('#userList .user-row').innerText(),/user3/);await p.getByLabel('账号状态筛选',{exact:true}).selectOption('unbound');assert.match(await p.locator('#userList .user-row').innerText(),/user4/);
await p.getByRole('button',{name:'重置账号筛选',exact:true}).click();await p.getByLabel('搜索账号或邮箱',{exact:true}).fill('user3 example');assert.equal(await p.locator('#userList .user-row').count(),11);await p.evaluate(()=>loadUserList());assert.equal(await p.getByLabel('搜索账号或邮箱',{exact:true}).inputValue(),'user3 example');await p.getByLabel('搜索账号或邮箱',{exact:true}).fill('preview-admin');assert.equal(await p.locator('#userList .user-row button').count(),0);
await p.getByLabel('搜索账号或邮箱',{exact:true}).fill('<img src=x>');assert.equal(await p.locator('#userList .user-row').count(),0);assert.equal(await p.locator('#userList img').count(),0);await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await p.evaluate(async()=>{api=async()=>{throw Error('offline');};await loadUserList();});await p.getByRole('button',{name:'重新加载',exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS account pagination, approval refresh, status/email filters, combined search, preserved filters, self protection, safe text, mobile and load failure recovery; no live account changes');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
